### ISSUE TITLE
Correct password was not recognized!

### ISSUE THREAD

**Issue by anarahmadov** [RedKatz/SocialMediaHackingToolkit#100]
Hey, I got some wordlist file. And I put my exact password to 4th place on wordlist file. Then I ran the program, But surprise, program could not find the correct password, just passed the password and tried to control next password. What was this? Could you please help me? Thanks in advance.

**Comment by RedKatz** [comment]
What operating system are you using?

**Comment by anarahmadov** [comment]
Windows 10

**Comment by TheZetsu** [comment]
@anarahmadov verify if the real password was written correctly and it match with lowercase and uppercase and has no spaces. I know it has little chances to be this the real problem but verify just in case.

**Comment by RedKatz** [comment]
With this answer I think I can close the issue, at least as far as the **current version** is concerned:

As far as **windows and termux** are concerned the program might sometimes struggle to recognize the password because of the ip tath is **banned**, this is because currently there is **no ip changer for windows or termux**, you would have to implement a proxy system, which would have to be updated every time, or made entered by the user, so as far as this version is concerned it is possible that on some **windows and termux** machines the correct password is not found, the social that should have less problems is instagram, _if it doesn't find the password there either your ip has been banned_ from their servers.

>if you fix this problem with termux and windows I will let you know here
